data('Artificial Intelligence','North America','United States','Massachusetts Institute of Technology (MIT)',1,'Department of Electrical Engineering & Computer Science (EECS)',1,'Artificial Intelligence','Almost all of the research by MIT EECS faculty, staff, and students is carried out in interdepartmental laboratories, centers, and programs. The primary labs include the Computer Science and Artificial Intelligence Lab (CSAIL), the Laboratory for Information and Decision Systems (LIDS), the Microsystems and Technology Laboratories (MTL) and the Research Laboratory of Electronics (RLE). For a complete list of laboratories, centers and programs at MIT, visit http://web.mit.edu/research/',1,3.7,1,7.5,1,'450','English',1,1,'US$ 25k+',30000,'US$ 1K - 2K',2000).
data('Applied CS','North America','United States','Massachusetts Institute of Technology (MIT)',1,'Department of Electrical Engineering & Computer Science (EECS)',1,'Applied CS','Almost all of the research by MIT EECS faculty, staff, and students is carried out in interdepartmental laboratories, centers, and programs. The primary labs include the Computer Science and Artificial Intelligence Lab (CSAIL), the Laboratory for Information and Decision Systems (LIDS), the Microsystems and Technology Laboratories (MTL) and the Research Laboratory of Electronics (RLE). For a complete list of laboratories, centers and programs at MIT, visit http://web.mit.edu/research/',1,3.7,1,8.5,1,'451','English',1,1,'US$ 25k+',30000,'US$ 1K - 2K',2000).
data('Information System','North America','United States','Massachusetts Institute of Technology (MIT)',1,'Department of Electrical Engineering & Computer Science (EECS)',1,'Information System ','Almost all of the research by MIT EECS faculty, staff, and students is carried out in interdepartmental laboratories, centers, and programs. The primary labs include the Computer Science and Artificial Intelligence Lab (CSAIL), the Laboratory for Information and Decision Systems (LIDS), the Microsystems and Technology Laboratories (MTL) and the Research Laboratory of Electronics (RLE). For a complete list of laboratories, centers and programs at MIT, visit http://web.mit.edu/research/',1,3.7,1,9.5,1,'452','English',1,1,'US$ 25k+',30000,'US$ 1K - 2K',2000).
data('Applied CS','North America','United States','Stanford University',7,'Computer Science (CS) Department',2,'Applied CS','Founded in 1965, the Stanford Computer Science (CS) Department continues to lead the world in computer science research and education. Throughout the past four decades, the Stanford CS Department has influenced society at levels that remain without parallel among academic institutions. Its spin-offs are among the most successful corporate ventures in the world, and many of the leaders in the academic and corporate research world are graduates of the Stanford CS Department',1.5,3.7,1,7.5,1,'550','English',1,1,'US$ 25k+',30000,'US$ 1K - 2K',2000).
data('Applied CS','North America','United States','Harvard University',4,'School of Engineering and Applied Science',17,'CS','Students interested in Computer Science may earn their Doctor of Philosophy through SEAS.  Doctoral students may earn the Master of Science (SM) degree en route to the Ph.D.  Additionally, some Harvard College students may be eligible to apply for the Bachelor of Arts and Master of Science (A.B./S.M.) program',1.5,3.7,1,0,1,'No Detail','English',1,1,'US$ 25k+',30000,'US$ 6K+',7000).
data('Applied CS','North America','United States','Harvard University',4,'School of Engineering and Applied Science',17,'Applied CS','Students interested in Computer Science may earn their Doctor of Philosophy through SEAS.  Doctoral students may earn the Master of Science (SM) degree en route to the Ph.D.  Additionally, some Harvard College students may be eligible to apply for the Bachelor of Arts and Master of Science (A.B./S.M.) program',1.5,3.7,1,0,1,'No Detail','English',1,1,'US$ 25k+',30000,'US$ 6K+',7000).
data('Artificial Intelligence','North America','Canada','University of Toronto',20,'Department of Computer Science',19,'Artificial Intelligence','How can we build and analyze systems for enabling users to communicate with computers using human language (also called natural language), and for automatically processing the vast amounts of data on the web available in the form of text? The focus covers appropriate material on natural language interfaces, as well as tools such as document summarization, intelligent search over the web, and so on. Students considering this focus are encouraged to consider a second Major in Linguistics.',1.5,3,1,0,0,'No Detail','English',1,1,'US$ 25k+',30000,'US$ 6K+',7000).
data('Applied CS','North America','Canada','University of Toronto',20,'Department of Computer Science',19,'Applied CS','How can we build and analyze systems for enabling users to communicate with computers using human language (also called natural language), and for automatically processing the vast amounts of data on the web available in the form of text? The focus covers appropriate material on natural language interfaces, as well as tools such as document summarization, intelligent search over the web, and so on. Students considering this focus are encouraged to consider a second Major in Linguistics.',1.5,3,1,0,0,'No Detail','English',1,1,'US$ 25k+',30000,'US$ 6K+',7000).
data('Computer Vision','North America','Canada','University of Toronto',20,'Department of Computer Science',19,'Computer Vision','How can we build and analyze systems for enabling users to communicate with computers using human language (also called natural language), and for automatically processing the vast amounts of data on the web available in the form of text? The focus covers appropriate material on natural language interfaces, as well as tools such as document summarization, intelligent search over the web, and so on. Students considering this focus are encouraged to consider a second Major in Linguistics.',1.5,3,1,0,0,'No Detail','English',1,1,'US$ 25k+',30000,'US$ 6K+',7000).
data('Applied CS','North America','Canada','University of Toronto',20,'Department of Computer Science',19,'Scientific Computing','How can we build and analyze systems for enabling users to communicate with computers using human language (also called natural language), and for automatically processing the vast amounts of data on the web available in the form of text? The focus covers appropriate material on natural language interfaces, as well as tools such as document summarization, intelligent search over the web, and so on. Students considering this focus are encouraged to consider a second Major in Linguistics.',1.5,3,1,0,0,'No Detail','English',1,1,'US$ 25k+',30000,'US$ 6K+',7000).
data('Artificial Intelligence','North America','Canada','University of Toronto',20,'Department of Computer Science',19,'Computational Linguistics & Natural Language Processing','How can we build and analyze systems for enabling users to communicate with computers using human language (also called natural language), and for automatically processing the vast amounts of data on the web available in the form of text? The focus covers appropriate material on natural language interfaces, as well as tools such as document summarization, intelligent search over the web, and so on. Students considering this focus are encouraged to consider a second Major in Linguistics.',1.5,3,1,0,0,'No Detail','English',1,1,'US$ 25k+',30000,'US$ 6K+',7000).
data('Applied CS','North America','United States','University of California Los Angeles (UCLA)',37,'Department of Computer Science',16,'Applied CS','-',1.5,3.5,1,7.5,1,'No Detail','English',1,1,'US$ 25k+',30000,'US$ 6K+',7000).
data('Technology Entrepreneurship','Europe','United Kingdom','University College London (UCL)',5,'School of Engineering Sciences',25,'Technology Enterpreneurship MSc','-',1,3.3,1,6.5,0,'No Detail','English',1,0,'US$ 25k+',30000,'US$ 2K - 4K',4000).
data('Software Engineering','Europe','United Kingdom','University College London (UCL)',5,'School of Engineering Sciences',25,'ICT Innovation MSc','-',1,3.3,1,6.5,0,'No Detail','English',1,0,'US$ 25k+',30000,'US$ 2K - 4K',4000).
data('Applied CS','Europe','United Kingdom','University of Oxford',5,'Department of Engineering Science',7,'MSc in Engineering Science','The MSc by Research in Engineering Science provides graduates with the opportunity to develop knowledge, understanding and expertise in their chosen field of engineering research, well beyond the level of a taught master’s degree, but without the requirement to complete as much novel research as a doctoral student. Students develop broad skills in relevant areas of mathematical and computational modelling, in the design and build of apparatus and software, and in data analytics and visualisation.',2,3.5,1,7.5,1,'750','English',1,1,'US$ 25k+',30000,'US$ 2K - 4K',4000).
data('Applied CS','Europe','United Kingdom','University of Cambridge',2,'Department of Computer Science and Technology',4,'MPhil in Advanced Computer Science','The aim of the course is to provide preparation appropriate for undertaking a PhD programme in computer science. Students take a mandatory course in Research Skills and select 5 taught modules from a wide range of advanced topics in computer science. Students also undertake a research project over two terms and submit a project report in mid-June. Research topic selection and planning occurs in the first term and the work is undertaken in subsequent terms. The taught modules are delivered in a range of styles. For example, there are traditional lecture courses, lecture courses with associated practical classes, reading clubs, and seminar style modules.',0.75,3.7,1,7.0,0,'No Detail','English',1,0,'US$ 25k+',30000,'US$ 4K - 6K',6000).
data('Applied CS','Europe','United Kingdom','University of Edinburgh',17,'School of Informatics Teaching',12,'Advanced Design Informatics MSc','Design informatics focuses on designing with data. This new course is run in conjunction with Edinburgh College of Art through the newly formed Centre for Design Informatics. On this programme you will learn how to build computational systems as well as the principles of design thinking and making. Through case studies of real-life products you will apply your knowledge in a practical way, developing an understanding of what it takes to create, design and take a product to market.',1,3,1,6.5,0,'No Detail','English',1,1,'US$ 25k+',30000,'US$ 2K - 4K',4000).
data('Artificial Intelligence','Europe','United Kingdom','University of Edinburgh',17,'School of Informatics',12,'Artificial Intelligence','This MSc is taught at the UK’s longest established centre for artificial intelligence, which remains one of the best in the world.',1,3,1,6.5,0,'No Detail','English',1,1,'US$ 25k+',30000,'US$ 2K - 4K',4000).
data('Applied CS','Europe','United Kingdom','University of Edinburgh',17,'School of Informatics',12,'Bioinformatics MSc','The aim of this MSc is to equip you with a strong background in biology, plus the computing skills and knowledge necessary to navigate the vast wealth of modern biological data. On completing this programme you will be able to take up PhD studies or bioinformatics posts in academia or in industry. The programme covers programming skills, statistical analysis and database science as well as bioinformatics. Option courses allow you to specialise in several aspects of bioinformatics.',1,3,1,6.5,0,'No Detail','English',1,1,'US$ 25k+',30000,'US$ 2K - 4K',4000).
data('Artificial Intelligence','Europe','United Kingdom','University of Edinburgh',17,'School of Informatics',12,'Cognition in Science and Society MSc','Students focus on core methodologies and theories of cognitive science, but also explore the synergy between cognitive science and its applications. This unifies forms of scholarly activity that are often pursued independently. You will develop the skills to embark on your own research project and will learn how to communicate research, so if you are interested in developing a research career or in working within science communication, this programme will provide an excellent foundation.',1,3.5,1,7.0,0,'No Detail','English',1,1,'US$ 25k+',30000,'US$ 2K - 4K',4000).
data('Artificial Intelligence','Europe','United Kingdom','University of Edinburgh',17,'School of Informatics',12,'Cognitive Science MSc','You will gain a thorough grounding in neural computation, formal logic, computational and theoretical linguistics, cognitive psychology and natural language processing, and through a vast range of optional courses you will develop your own interests in this fascinating field.',1,3,1,6.5,0,'No Detail','English',1,1,'US$ 25k+',30000,'US$ 2K - 4K',4000).
data('Applied CS','Europe','United Kingdom','University of Edinburgh',17,'School of Informatics',12,'Computer Science MSc','This MSc will give you specialist knowledge in the design, implementation and use of computing systems ranging from the components of a single processor to computer networks as vast as the internet.',1,3,1,6.5,0,'No Detail','English',1,1,'US$ 25k+',30000,'US$ 2K - 4K',4000).
data('Applied CS','Europe','United Kingdom','University of Edinburgh',17,'School of Informatics',12,'Design Informatics MSc','Design informatics focuses on designing with data. This new course is run in conjunction with Edinburgh College of Art through the newly formed Centre for Design Informatics. On this programme you will learn how to build computational systems as well as the principles of design thinking and making. Through case studies of real-life products you will apply your knowledge in a practical way, developing an understanding of what it takes to create, design and take a product to market.',1,3,1,6.5,0,'No Detail','English',1,1,'US$ 25k+',30000,'US$ 2K - 4K',4000).
data('Applied CS','Europe','United Kingdom','University of Edinburgh',17,'School of Informatics',12,'Informatics MSc','Informatics is the study of how natural and artificial systems store, process and communicate information. Edinburgh has a long-standing tradition of world-class research and teaching in informatics, a discipline central to a new enlightenment in scholarship and learning, and critical to the future development of science, technology and society.',1,3,1,6.5,0,'No Detail','English',1,1,'US$ 25k+',30000,'US$ 2K - 4K',4000).
data('Artificial Intelligence','Europe','United Kingdom','University of Edinburgh',17,'School of Informatics',12,'Speech and Language Processing MSc','This intensive programme offers an exciting opportunity to learn from world leaders in both informatics and linguistics. Drawing from our cutting-edge research, the programme’s content covers all areas of speech and language processing, from phonetics, speech synthesis and speech recognition to natural language generation and machine translation. This flexible programme provides research or vocational training and can be either freestanding or lead to PhD study. The modular nature of the programme allows you to tailor it to your own interests.',1,3,1,7.0,0,'No Detail','English',1,1,'US$ 25k+',30000,'US$ 2K - 4K',4000).
data('Software Engineering','Europe','Sweden','Uppsala University',81,'Department of Information Technology',151,'Software Technology','The Department of Information Technology is unique in its breadth. Our activities span from the gathering and management of data via signal processing, scientific computing and control engineering to communication of results with the aid of database management and human-computer interaction. A common ground is provided by research in theoretical computing science, real-time systems, and computer architecture.',2,0,1,6.5,0,'No Detail','English',0,1,'US$ 25k+',30000,'US$ 6K+',7000).
data('Artificial Intelligence','Europe','Sweden','Uppsala University',81,'Department of Information Technology',151,'Artificial Intelligence','The Department of Information Technology is unique in its breadth. Our activities span from the gathering and management of data via signal processing, scientific computing and control engineering to communication of results with the aid of database management and human-computer interaction. A common ground is provided by research in theoretical computing science, real-time systems, and computer architecture.',2,0,1,6.5,0,'No Detail','English',0,1,'US$ 25k+',30000,'US$ 6K+',7000).
data('Applied CS','Europe','Sweden','Uppsala University',81,'Department of Information Technology',151,'Computational Science','The Department of Information Technology is unique in its breadth. Our activities span from the gathering and management of data via signal processing, scientific computing and control engineering to communication of results with the aid of database management and human-computer interaction. A common ground is provided by research in theoretical computing science, real-time systems, and computer architecture.',2,0,1,6.5,0,'No Detail','English',0,1,'US$ 25k+',30000,'US$ 6K+',7000).
data('Applied CS','Europe','United Kingdom','University of Oxford',5,'Depatment of Computer Science',7,'Computer Science','The MSc in Computer Science at Oxford has been designed to teach the mathematical principles of specification, design and efficient implementation of both software and hardware. This course is intended for graduates in computer science as well as graduates in other numerate disciplines who have some training or experience in programming.',1,3.5,1,8.0,0,'No Detail','English',1,1,'US$ 25k+',30000,'US$ 2K - 4K',4000).
data('Software Engineering','Europe','United Kingdom','University of Oxford',5,'Depatment of Computer Science',7,'Software Engineering','The MSc in Computer Science at Oxford has been designed to teach the mathematical principles of specification, design and efficient implementation of both software and hardware. This course is intended for graduates in computer science as well as graduates in other numerate disciplines who have some training or experience in programming.',4,3.5,1,8.0,0,'No Detail','English',1,1,'US$ 25k+',30000,'US$ 2K - 4K',4000).
data('Network and Security','Europe','United Kingdom','University of Oxford',5,'Depatment of Computer Science',7,'Software and Systems Security','A security professional needs to understand principles of architecture, design, management, interoperability, and evolution, and to apply them effectively in a world of rapidly-changing technologies and expectations. The MSc in Software and Systems Security teaches these principles and their application.',4,3.5,1,8.0,0,'No Detail','English',1,1,'US$ 25k+',30000,'US$ 2K - 4K',4000).
data('Applied CS','Europe','United Kingdom','Imperial College London',2,'Department of Computing',13,'Computing Science','This course provides a year of intensive training in computer science and is suitable for graduates of disciplines other than computing who are preparing for a career in the computer industry.',1,3,1,6.5,0,'No Detail','English',1,0,'US$ 25k+',30000,'US$ 2K - 4K',4000).
data('Applied CS','Europe','United Kingdom','Imperial College London',2,'Department of Computing',13,'Advanced Computing MSc','This course provides a year of intensive training in computer science and is suitable for graduates of disciplines other than computing who are preparing for a career in the computer industry.',1,3,1,6.5,0,'No Detail','English',1,0,'US$ 25k+',30000,'US$ 2K - 4K',4000).
data('Applied CS','Asia','Singapore','National University of Singapore?NUS?',22,'Faculty of Computing',9,'Computer Engineering','-',2,3,1,6.0,1,'1350','English',0,0,'US$ 10K - 15K',15000,'US$ 4K - 6K',6000).
data('Network and Security','Asia','Hong Kong','The Hong Kong University of Science and Technology?HKUST?',40,'Faculty of Computer Science',11,'Network','-',2,3,1,5.5,0,'No Detail','English',0,1,'US$ 5K - 10K',10000,'US$ 6K+',7000).
data('Software Engineering','Asia','Hong Kong','The Hong Kong University of Science and Technology?HKUST?',40,'Faculty of Computer Science',11,'Software Technology','-',2,3,1,5.5,0,'No Detail','English',0,1,'US$ 5K - 10K',10000,'US$ 6K+',7000).
data('Artificial Intelligence','Asia','Hong Kong','The Hong Kong University of Science and Technology?HKUST?',40,'Faculty of Computer Science',11,'Artificial Intelligence','-',2,3,1,5.5,0,'No Detail','English',0,1,'US$ 5K - 10K',10000,'US$ 6K+',7000).
data('Applied CS','Asia','Hong Kong','The Hong Kong University of Science and Technology?HKUST?',40,'Faculty of Computer Science',11,'Applied CS','-',2,3,1,5.5,0,'No Detail','English',0,1,'US$ 5K - 10K',10000,'US$ 6K+',7000).
data('Network and Security','Asia','Singapore','National University of Singapore?NUS?',22,'School of Computing',9,'Network','-',2,3.3,1,7.0,1,'320','English',0,1,'US$ 10K - 15K',15000,'US$ 4K - 6K',6000).
data('Software Engineering','Asia','Singapore','National University of Singapore?NUS?',22,'School of Computing',9,'Software Technology','-',2,3.3,1,7.0,1,'320','English',0,1,'US$ 10K - 15K',15000,'US$ 4K - 6K',6000).
data('Artificial Intelligence','Asia','Singapore','National University of Singapore?NUS?',22,'School of Computing',9,'Artificial Intelligence','-',2,3.3,1,7.0,1,'320','English',0,1,'US$ 10K - 15K',15000,'US$ 4K - 6K',6000).
data('Applied CS','Asia','Singapore','National University of Singapore?NUS?',22,'School of Computing',9,'Applied CS','-',2,3.3,1,7.0,1,'320','English',0,1,'US$ 10K - 15K',15000,'US$ 4K - 6K',6000).
data('Network and Security','Asia','Hong Kong','The Hong Kong University of Science and Technology?HKUST?',40,'School of Engineering',11,'Network','-',2,3.3,1,6.0,1,'No Detail','English',0,1,'US$ 10K - 15K',15000,'US$ 6K+',7000).
data('Software Engineering','Asia','Hong Kong','The Hong Kong University of Science and Technology?HKUST?',40,'School of Engineering',11,'Software Technology','-',2,3.3,1,6.0,1,'No Detail','English',0,1,'US$ 10K - 15K',15000,'US$ 6K+',7000).
data('Artificial Intelligence','Asia','Hong Kong','The Hong Kong University of Science and Technology?HKUST?',40,'School of Engineering',11,'Artificial Intelligence','-',2,3.3,1,6.0,1,'No Detail','English',0,1,'US$ 10K - 15K',15000,'US$ 6K+',7000).
data('Applied CS','Asia','Hong Kong','The Hong Kong University of Science and Technology?HKUST?',40,'School of Engineering',11,'Applied CS','-',2,3.3,1,6.0,1,'No Detail','English',0,1,'US$ 10K - 15K',15000,'US$ 6K+',7000).
data('Network and Security','Asia','Hong Kong','The University of Hong Kong?UHK?',28,'Faculty of Engineering',14,'Network','-',2,3.3,1,6.5,0,'No Detail','English',0,1,'US$ 10K - 15K',15000,'US$ 6K+',7000).
data('Software Engineering','Asia','Hong Kong','The University of Hong Kong?UHK?',28,'Faculty of Engineering',14,'Software Technology','-',2,3.3,1,6.5,0,'No Detail','English',0,1,'US$ 10K - 15K',15000,'US$ 6K+',7000).
data('Artificial Intelligence','Asia','Hong Kong','The University of Hong Kong?UHK?',28,'Faculty of Engineering',14,'Artificial Intelligence','-',2,3.3,1,6.5,0,'No Detail','English',0,1,'US$ 10K - 15K',15000,'US$ 6K+',7000).
data('Applied CS','Asia','Hong Kong','The University of Hong Kong?UHK?',28,'Faculty of Engineering',14,'Applied CS','-',2,3.3,1,6.5,0,'No Detail','English',0,1,'US$ 10K - 15K',15000,'US$ 6K+',7000).
data('Applied CS','Asia','Indonesia','Universitas Indonesia',306,'Fakultas Ilmu komputer',200,'Applied CS','information system is the liaison between the department of computer science with the client',4,3,0,0,0,'No Detail','indonesia english',1,1,'US$ 5K - 10K',10000,'US$ 1K - 2K',2000).
data('Artificial Intelligence','Asia','Japan ','University of Tokyo',31,'ENGINEERING AND TECHNOLOGY DEGREES',20,'Artificial Intelligence','-',2,2,1,6.5,0,'No Detail','Japanese',0,1,'US$ 5K - 10K',10000,'US$ 6K+',7000).
data('Applied CS','Asia','Japan ','University of Tokyo',31,'ENGINEERING AND TECHNOLOGY DEGREES',20,'Applied CS','-',2,2,1,6.5,0,'No Detail','Japanese',0,1,'US$ 5K - 10K',10000,'US$ 6K+',7000).
data('Computer Vision','Asia','Japan ','University of Tokyo',31,'ENGINEERING AND TECHNOLOGY DEGREES',20,'Computer graphics','-',2,2,1,6.5,0,'No Detail','Japanese',0,1,'US$ 5K - 10K',10000,'US$ 6K+',7000).
data('Artificial Intelligence','Asia','South Korea','Seoul National University?SNU?',31,'College of Engineering',42,'Artificial Intelligence','-',2,3,0,0,0,'No Detail','Korean',0,1,'US$ 5K - 10K',10000,'US$ 2K - 4K',4000).
data('Applied CS','Asia','South Korea','Seoul National University?SNU?',31,'College of Engineering',42,'Applied CS','-',2,3,0,0,0,'No Detail','Korean',0,1,'US$ 5K - 10K',10000,'US$ 2K - 4K',4000).
data('Applied CS','Asia','South Korea','Seoul National University?SNU?',31,'College of Engineering',42,'Programming language theory','-',2,3,0,0,0,'No Detail','Korean',0,1,'US$ 5K - 10K',10000,'US$ 2K - 4K',4000).
data('Network and Security','Asia','Hong Kong','The Chinese University of Hong Kong?CUHK?',46,'Department of Computer Science&Engineering',18,'Network','-',2,3,1,6.5,0,'No Detail','Chinese',0,1,'US$ 10K - 15K',15000,'US$ 2K - 4K',4000).
data('Software Engineering','Asia','Hong Kong','The Chinese University of Hong Kong?CUHK?',46,'Department of Computer Science&Engineering',18,'Software Technology','-',2,3,1,6.5,0,'No Detail','Chinese',0,1,'US$ 10K - 15K',15000,'US$ 2K - 4K',4000).
data('Artificial Intelligence','Asia','Hong Kong','The Chinese University of Hong Kong?CUHK?',46,'Department of Computer Science&Engineering',18,'Artificial Intelligence','-',2,3,1,6.5,0,'No Detail','Chinese',0,1,'US$ 10K - 15K',15000,'US$ 2K - 4K',4000).
data('Applied CS','Asia','Hong Kong','The Chinese University of Hong Kong?CUHK?',46,'Department of Computer Science&Engineering',18,'Applied CS','-',2,3,1,6.5,0,'No Detail','Chinese',0,1,'US$ 10K - 15K',15000,'US$ 2K - 4K',4000).
data('Network and Security','Asia','Singapore','Nanyang Technological University (NTU)',39,'School of Computer Engineering',21,'Network','-',2,3.3,1,7.0,0,'No Detail','English',0,1,'US$ 5K - 10K',10000,'US$ 4K - 6K',6000).
data('Software Engineering','Asia','Singapore','Nanyang Technological University (NTU)',39,'School of Computer Engineering',21,'Software Technology','-',2,3.3,1,7.0,0,'No Detail','English',0,1,'US$ 5K - 10K',10000,'US$ 4K - 6K',6000).
data('Artificial Intelligence','Asia','Singapore','Nanyang Technological University (NTU)',39,'School of Computer Engineering',21,'Artificial Intelligence','-',2,3.3,1,7.0,0,'No Detail','English',0,1,'US$ 5K - 10K',10000,'US$ 4K - 6K',6000).
data('Applied CS','Asia','Singapore','Nanyang Technological University (NTU)',39,'School of Computer Engineering',21,'Applied CS','-',2,3.3,1,7.0,0,'No Detail','English',0,1,'US$ 5K - 10K',10000,'US$ 4K - 6K',6000).
data('Network and Security','Asia','China','Tsinghua University',47,'Department of Computer Science and Technology',34,'Network','-',2,2,0,0,0,'No Detail','Chinese',0,1,'US$ 5K - 10K',10000,'US$ 1K - 2K',2000).
data('Software Engineering','Asia','China','Tsinghua University',47,'Department of Computer Science and Technology',34,'Software Technology','-',2,2,0,0,0,'No Detail','Chinese',0,1,'US$ 5K - 10K',10000,'US$ 1K - 2K',2000).
data('Applied CS','Asia','China','Tsinghua University',47,'Department of Computer Science and Technology',34,'Applied CS','-',2,2,0,0,0,'No Detail','Chinese',0,1,'US$ 5K - 10K',10000,'US$ 1K - 2K',2000).
data('Network and Security','Asia','China','Peking University',57,'College of  Information Science Technology',35,'Network','-',2,2,0,0,0,'No Detail','Chinese',0,1,'US$ 5K - 10K',10000,'US$ 1K - 2K',2000).
data('Software Engineering','Asia','China','Peking University',57,'College of  Information Science Technology',35,'Software Technology','-',2,2,0,0,0,'No Detail','Chinese',0,1,'US$ 5K - 10K',10000,'US$ 1K - 2K',2000).
data('Artificial Intelligence','Asia','China','Peking University',57,'College of  Information Science Technology',35,'Artificial Intelligence','-',2,2,0,0,0,'No Detail','Chinese',0,1,'US$ 5K - 10K',10000,'US$ 1K - 2K',2000).
data('Applied CS','Asia','China','Peking University',57,'College of  Information Science Technology',35,'Applied CS','-',2,2,0,0,0,'No Detail','Chinese',0,1,'US$ 5K - 10K',10000,'US$ 1K - 2K',2000).
data('Network and Security','Asia','South Korea','Korea Advanced Institute of Science & Technology?KAIST ?',51,'College of Information Science & Technology',36,'Network','-',2,2,1,0,0,'No Detail','Korean',0,1,'US$ 20K - 25K',25000,'US$ 2K - 4K',4000).
data('Software Engineering','Asia','South Korea','Korea Advanced Institute of Science & Technology?KAIST ?',51,'College of Information Science & Technology',36,'Software Technology','-',2,2,1,0,0,'No Detail','Korean',0,1,'US$ 20K - 25K',25000,'US$ 2K - 4K',4000).
data('Artificial Intelligence','Asia','South Korea','Korea Advanced Institute of Science & Technology?KAIST ?',51,'College of Information Science & Technology',36,'Artificial Intelligence','-',2,2,1,0,0,'No Detail','Korean',0,1,'US$ 20K - 25K',25000,'US$ 2K - 4K',4000).
data('Applied CS','Asia','South Korea','Korea Advanced Institute of Science & Technology?KAIST ?',51,'College of Information Science & Technology',36,'Applied CS','-',2,2,1,0,0,'No Detail','Korean',0,1,'US$ 20K - 25K',25000,'US$ 2K - 4K',4000).
data('Network and Security','Asia','Hong Kong','The Hong Kong Polytechnic University?PolyU?',162,'Faculty of Engineering/Department of Computing',50,'Network','-',2,3,1,6.5,0,'No Detail','English',1,1,'US$ 10K - 15K',15000,'US$ 2K - 4K',4000).
data('Software Engineering','Asia','Hong Kong','The Hong Kong Polytechnic University?PolyU?',162,'Faculty of Engineering/Department of Computing',50,'Software Technology','-',2,3,1,6.5,0,'No Detail','English',1,1,'US$ 10K - 15K',15000,'US$ 2K - 4K',4000).
data('Artificial Intelligence','Asia','Hong Kong','The Hong Kong Polytechnic University?PolyU?',162,'Faculty of Engineering/Department of Computing',50,'Artificial Intelligence','-',2,3,1,6.5,0,'No Detail','English',1,1,'US$ 10K - 15K',15000,'US$ 2K - 4K',4000).
data('Applied CS','Asia','Hong Kong','The Hong Kong Polytechnic University?PolyU?',162,'Faculty of Engineering/Department of Computing',50,'Applied CS','-',2,3,1,6.5,0,'No Detail','English',1,1,'US$ 10K - 15K',15000,'US$ 2K - 4K',4000).
data('Network and Security','Asia','Hong Kong','City University of Hong Kong',108,'Department of Computer Science',61,'Network','-',2,3,1,6.5,0,'No Detail','English',0,1,'US$ 10K - 15K',15000,'US$ 2K - 4K',4000).
data('Software Engineering','Asia','Hong Kong','City University of Hong Kong',108,'Department of Computer Science',61,'Software Technology','-',2,3,1,6.5,0,'No Detail','English',0,1,'US$ 10K - 15K',15000,'US$ 2K - 4K',4000).
data('Artificial Intelligence','Asia','Hong Kong','City University of Hong Kong',108,'Department of Computer Science',61,'Artificial Intelligence','-',2,3,1,6.5,0,'No Detail','English',0,1,'US$ 10K - 15K',15000,'US$ 2K - 4K',4000).
data('Applied CS','Asia','Hong Kong','City University of Hong Kong',108,'Department of Computer Science',61,'Applied CS','-',2,3,1,6.5,0,'No Detail','English',0,1,'US$ 10K - 15K',15000,'US$ 2K - 4K',4000).
data('Network and Security','Asia','Japan ','Kyoto University',36,'Faculty of Engineering',51100,'Network','-',2,2,1,6.5,0,'No Detail','Japanese',0,1,'US$ 5K - 10K',10000,'US$ 6K+',7000).
data('Software Engineering','Asia','Japan ','Kyoto University',36,'Faculty of Engineering',51100,'Software Technology','-',2,2,1,6.5,0,'No Detail','Japanese',0,1,'US$ 5K - 10K',10000,'US$ 6K+',7000).
data('Artificial Intelligence','Asia','Japan ','Kyoto University',36,'Faculty of Engineering',51100,'Artificial Intelligence','-',2,2,1,6.5,0,'No Detail','Japanese',0,1,'US$ 5K - 10K',10000,'US$ 6K+',7000).
data('Applied CS','Asia','Japan ','Kyoto University',36,'Faculty of Engineering',51100,'Applied CS','-',2,2,1,6.5,0,'No Detail','Japanese',0,1,'US$ 5K - 10K',10000,'US$ 6K+',7000).
data('Network and Security','Asia','Japan ','Osaka University',55,'Graduate School of Infromation Science',51100,'Network','-',2,2,1,0,1,'No Detail','Japanese',0,1,'US$ 5K - 10K',10000,'US$ 6K+',7000).
data('Applied CS','Asia','Japan ','Osaka University',55,'Graduate School of Infromation Science',51100,'Applied CS','-',2,2,1,0,1,'No Detail','Japanese',0,1,'US$ 5K - 10K',10000,'US$ 6K+',7000).
data('Multimedia','Asia','Japan ','Osaka University',55,'Graduate School of Infromation Science',51100,'Multimedia','-',2,2,1,0,1,'No Detail','Japanese',0,1,'US$ 5K - 10K',10000,'US$ 6K+',7000).
data('Network and Security','Asia','Japan ','Tokyo Institute of Technology (Tokyo Tech, Tokodai)',68,'Graduate School of Information Science and Engineering',51100,'Network','-',2,2,1,0,0,'No Detail','Japanese',0,1,'US$ 10K - 15K',15000,'US$ 6K+',7000).
data('Software Engineering','Asia','Japan ','Tokyo Institute of Technology (Tokyo Tech, Tokodai)',68,'Graduate School of Information Science and Engineering',51100,'Software Technology','-',2,2,1,0,0,'No Detail','Japanese',0,1,'US$ 10K - 15K',15000,'US$ 6K+',7000).
data('Artificial Intelligence','Asia','Japan ','Tokyo Institute of Technology (Tokyo Tech, Tokodai)',68,'Graduate School of Information Science and Engineering',51100,'Artificial Intelligence','-',2,2,1,0,0,'No Detail','Japanese',0,1,'US$ 10K - 15K',15000,'US$ 6K+',7000).
data('Applied CS','Asia','Japan ','Tokyo Institute of Technology (Tokyo Tech, Tokodai)',68,'Graduate School of Information Science and Engineering',51100,'Applied CS','-',2,2,1,0,0,'No Detail','Japanese',0,1,'US$ 10K - 15K',15000,'US$ 6K+',7000).
data('Network and Security','Asia','China','Fudan University',71,'School of Computer Science/School of Information Science and Technology/School of Software Engineering',51100,'Network','-',2,2,0,0,0,'No Detail','Chinese',0,1,'US$ 5K - 10K',10000,'US$ 1K - 2K',2000).
data('Software Engineering','Asia','China','Fudan University',71,'School of Computer Science/School of Information Science and Technology/School of Software Engineering',51100,'Software Technology','-',2,2,0,0,0,'No Detail','Chinese',0,1,'US$ 5K - 10K',10000,'US$ 1K - 2K',2000).
data('Applied CS','Asia','China','Fudan University',71,'School of Computer Science/School of Information Science and Technology/School of Software Engineering',51100,'Applied CS','-',2,2,0,0,0,'No Detail','Chinese',0,1,'US$ 5K - 10K',10000,'US$ 1K - 2K',2000).
data('Artificial Intelligence','Asia','Japan ','Tohoku University',71,'School of Enginering',151200,'Artificial Intelligence','-',2,2,1,0,0,'No Detail','Japanese',0,1,'US$ 5K - 10K',10000,'US$ 2K - 4K',4000).
data('Artificial Intelligence','Asia','Japan ','Tohoku University',71,'School of Enginering',151200,'Robot','-',2,2,1,0,0,'No Detail','Japanese',0,1,'US$ 5K - 10K',10000,'US$ 2K - 4K',4000).
data('Network and Security','Asia','Taiwan','National Taiwan University (NTU)',76,'The Graduate Institute of Networking and Multimedia (GINM)',45,'Network','-',2,3,1,5.5,0,'No Detail','Chinese&English',0,1,'US$ 5K - 10K',10000,'US$ 2K - 4K',4000).
data('Multimedia','Asia','Taiwan','National Taiwan University (NTU)',76,'The Graduate Institute of Networking and Multimedia (GINM)',45,'Multimedia','-',2,3,1,5.5,0,'No Detail','Chinese&English',0,1,'US$ 5K - 10K',10000,'US$ 2K - 4K',4000).
data('Network and Security','Asia','South Korea','Pohang University of Science And Technology (POSTECH)',86,'Department of Computer Science & Engineering',101150,'Network','-',2,3.3,0,0,0,'No Detail','Korean',0,1,'US$ 5K - 10K',10000,'US$ 6K+',7000).
data('Software Engineering','Asia','South Korea','Pohang University of Science And Technology (POSTECH)',86,'Department of Computer Science & Engineering',101150,'Software Technology','-',2,3.3,0,0,0,'No Detail','Korean',0,1,'US$ 5K - 10K',10000,'US$ 6K+',7000).
data('Applied CS','Asia','South Korea','Pohang University of Science And Technology (POSTECH)',86,'Department of Computer Science & Engineering',101150,'Applied CS','-',2,3.3,0,0,0,'No Detail','Korean',0,1,'US$ 5K - 10K',10000,'US$ 6K+',7000).
data('Artificial Intelligence','Asia','South Korea','Pohang University of Science And Technology (POSTECH)',86,'Department of Computer Science & Engineering',101150,'Artificial Intelligence','-',2,3.3,0,0,0,'No Detail','Korean',0,1,'US$ 5K - 10K',10000,'US$ 6K+',7000).
data('Applied CS','Asia','Japan ','Nagoya University',102,'Graduate School of Information Science',200300,'Applied CS','Graduate Departments: 1.Computer Science and Mathematical Informatics 2.Information Engineering 3.Media Science 4.Complex Systems Science 5.Systems and Social Informatics',2,2,1,6.5,0,'No Detail','Japanese',0,1,'US$ 5K - 10K',10000,'US$ 4K - 6K',6000).
data('Software Engineering','Asia','China','Shanghai Jiao Tong University',104,'School of Software',51100,'Software Technology','-',2,2,0,0,0,'No Detail','Chinese',1,1,'US$ 5K - 10K',10000,'US$ 2K - 4K',4000).
data('Network and Security','Asia','South Korea','Yonsei University',106,'College of Engineering',151200,'Network','-',2,2,1,0,0,'No Detail','Korean',0,1,'US$ 5K - 10K',10000,'US$ 4K - 6K',6000).
data('Software Engineering','Asia','South Korea','Yonsei University',106,'College of Engineering',151200,'Software Technology','-',2,2,1,0,0,'No Detail','Korean',0,1,'US$ 5K - 10K',10000,'US$ 4K - 6K',6000).
data('Applied CS','Asia','South Korea','Yonsei University',106,'College of Engineering',151200,'Applied CS','-',2,2,1,0,0,'No Detail','Korean',0,1,'US$ 5K - 10K',10000,'US$ 4K - 6K',6000).
data('Artificial Intelligence','Asia','South Korea','Yonsei University',106,'College of Engineering',151200,'Artificial Intelligence','-',2,2,1,0,0,'No Detail','Korean',0,1,'US$ 5K - 10K',10000,'US$ 4K - 6K',6000).
data('Network and Security','Asia','South Korea','Korea University',116,'College of Information and Communications',151,'Network','-',2,2,0,0,0,'No Detail','Korean',0,1,'US$ 10K - 15K',15000,'US$ 4K - 6K',6000).
data('Network and Security','Asia','Japan ','kyushu university',126,'Faculty of Information Science and Electrical Engineering',151,'Network','-',2,1,0,0,0,'No Detail','Japanese',0,1,'US$ 5K - 10K',10000,'US$ 6K+',7000).
data('Artificial Intelligence','Asia','Japan ','kyushu university',126,'Faculty of Information Science and Electrical Engineering',151,'Artificial Intelligence','-',2,1,0,0,0,'No Detail','Japanese',0,1,'US$ 5K - 10K',10000,'US$ 6K+',7000).
data('Network and Security','Asia','Japan ','Hokkaido University',135,'Faculty Information science and technology',200,'Network','-',2,2,0,0,0,'No Detail','Japanese',0,1,'US$ 5K - 10K',10000,'US$ 6K+',7000).
data('Software Engineering','Asia','Japan ','Hokkaido University',135,'Faculty Information science and technology',200,'Software Technology','-',2,2,0,0,0,'No Detail','Japanese',0,1,'US$ 5K - 10K',10000,'US$ 6K+',7000).
data('Applied CS','Asia','Japan ','Hokkaido University',135,'Faculty Information science and technology',200,'Applied CS','-',2,2,0,0,0,'No Detail','Japanese',0,1,'US$ 5K - 10K',10000,'US$ 6K+',7000).
data('Artificial Intelligence','Asia','Japan ','Hokkaido University',135,'Faculty Information science and technology',200,'Artificial Intelligence','-',2,2,0,0,0,'No Detail','Japanese',0,1,'US$ 5K - 10K',10000,'US$ 6K+',7000).
data('Software Engineering','Asia','Israel','Hebrew University of Jerusalem',138,'Faculty of Computer Science',200,'Software Technology','-',2,3,1,0,0,'No Detail','Hebrew&English',0,1,'US$ 10K - 15K',10000,'US$ 6K+',7000).
data('Network and Security','Asia','South Korea','Sungkyunkwan University',140,'Faculty of Computer&Electronic Engineering',101,'Network','-',2,1,0,0,0,'No Detail','Korean',0,1,'US$ 5K - 10K',10000,'US$ 6K+',7000).
data('Software Engineering','Asia','South Korea','Sungkyunkwan University',140,'Faculty of Computer&Electronic Engineering',101,'Software Technology','-',2,1,0,0,0,'No Detail','Korean',0,1,'US$ 5K - 10K',10000,'US$ 6K+',7000).
data('Artificial Intelligence','Asia','South Korea','Sungkyunkwan University',140,'Faculty of Computer&Electronic Engineering',101,'Artificial Intelligence','-',2,1,0,0,0,'No Detail','Korean',0,1,'US$ 5K - 10K',10000,'US$ 6K+',7000).
data('Network and Security','Asia','China','Zhejiang University',144,'Faculty of Information Technology',51,'Network','-',2,2,0,0,0,'No Detail','Chinese',0,1,'US$ 5K - 10K',10000,'US$ 2K - 4K',4000).
data('Software Engineering','Asia','China','Zhejiang University',144,'Faculty of Information Technology',51,'Software Technology','-',2,2,0,0,0,'No Detail','Chinese',0,1,'US$ 5K - 10K',10000,'US$ 2K - 4K',4000).
data('Artificial Intelligence','Asia','China','Zhejiang University',144,'Faculty of Information Technology',51,'Artificial Intelligence','-',2,2,0,0,0,'No Detail','Chinese',0,1,'US$ 5K - 10K',10000,'US$ 2K - 4K',4000).
data('Applied CS','Asia','China','Zhejiang University',144,'Faculty of Information Technology',51,'Applied CS','-',2,2,0,0,0,'No Detail','Chinese',0,1,'US$ 5K - 10K',10000,'US$ 2K - 4K',4000).
data('Network and Security','Asia','China','University of Science and Technology of China',147,'School of Computer Science and Technology',51,'Network','-',2,2,0,0,0,'No Detail','Chinese',1,1,'US$ 5K - 10K',10000,'US$ 2K - 4K',4000).
data('Software Engineering','Asia','China','University of Science and Technology of China',147,'School of Computer Science and Technology',51,'Software Technology','-',2,2,0,0,0,'No Detail','Chinese',1,1,'US$ 5K - 10K',10000,'US$ 2K - 4K',4000).
data('Applied CS','Asia','China','University of Science and Technology of China',147,'School of Computer Science and Technology',51,'Applied CS','-',2,2,0,0,0,'No Detail','Chinese',1,1,'US$ 5K - 10K',10000,'US$ 2K - 4K',4000).
data('Network and Security','Asia','Malaysia','Universiti Malaya (UM)',151,'-',2,3,1,6.0,0,'No Detail','English',0,1,'US$ 5K - 10K',10000,'US$ 2K - 4K',4000).
data('Software Engineering','Asia','Malaysia','Universiti Malaya (UM)',151,'-',2,3,1,6.0,0,'No Detail','English',0,1,'US$ 5K - 10K',10000,'US$ 2K - 4K',4000).
data('Artificial Intelligence','Asia','Malaysia','Universiti Malaya (UM)',151,'Faculty of Computer Science and Information Technology',51,'Artificial Intelligence','-',2,3,1,6.0,0,'No Detail','English',0,1,'US$ 5K - 10K',10000,'US$ 2K - 4K',4000).
data('Applied CS','Asia','Malaysia','Universiti Malaya (UM)',151,'-',2,3,1,6.0,0,'No Detail','English',0,1,'US$ 5K - 10K',10000,'US$ 2K - 4K',4000).
data('Network and Security','Asia','China','Nanjing University',162,'Department of Computer Science and Technology',51,'Network','-',2,2,0,0,0,'No Detail','Chinese',0,1,'US$ 5K - 10K',10000,'US$ 2K - 4K',4000).
data('Software Engineering','Asia','China','Nanjing University',162,'Department of Computer Science and Technology',51,'Software Technology','-',2,2,0,0,0,'No Detail','Chinese',0,1,'US$ 5K - 10K',10000,'US$ 2K - 4K',4000).
data('Artificial Intelligence','Asia','China','Nanjing University',162,'Department of Computer Science and Technology',101,'Artificial Intelligence','-',2,2,0,0,0,'No Detail','Chinese',0,1,'US$ 5K - 10K',10000,'US$ 2K - 4K',4000).
data('Applied CS','Asia','China','Nanjing University',162,'Department of Computer Science and Technology',101,'Applied CS','-',2,2,0,0,0,'No Detail','Chinese',0,1,'US$ 5K - 10K',10000,'US$ 2K - 4K',4000).
data('Network and Security','Asia','Hong Kong','The Hong Kong Polytechnic University',162,'Faculty of Engineering',50,'Network','-',2,3,1,6.0,0,'No Detail','Chinese/English',0,1,'US$ 10K - 15K',15000,'US$ 2K - 4K',4000).
data('Software Engineering','Asia','Hong Kong','The Hong Kong Polytechnic University',162,'Faculty of Engineering',50,'Software Technology','-',2,3,1,6.0,0,'No Detail','Chinese/English',0,1,'US$ 10K - 15K',15000,'US$ 2K - 4K',4000).
data('Artificial Intelligence','Asia','Hong Kong','The Hong Kong Polytechnic University',162,'Faculty of Engineering',50,'Artificial Intelligence','-',2,3,1,6.0,0,'No Detail','Chinese/English',0,1,'US$ 10K - 15K',15000,'US$ 2K - 4K',4000).
data('Applied CS','Asia','Hong Kong','The Hong Kong Polytechnic University',162,'Faculty of Engineering',50,'Applied CS','-',2,3,1,6.0,0,'No Detail','Chinese/English',0,1,'US$ 10K - 15K',15000,'US$ 2K - 4K',4000).
data('Network and Security','Asia','Israel','Technion - Israel Institute of Technology',165,'Faculty of Computer Science',200,'Network','-',2,3,1,0,0,'No Detail','Hebrew/English',0,1,'US$ 5K - 10K',10000,'US$ 6K+',7000).
data('Software Engineering','Asia','Israel','Technion - Israel Institute of Technology',165,'Faculty of Computer Science',200,'Software Technology','-',2,3,1,0,0,'No Detail','Hebrew/English',0,1,'US$ 5K - 10K',10000,'US$ 6K+',7000).
data('Artificial Intelligence','Asia','Israel','Technion - Israel Institute of Technology',165,'Faculty of Computer Science',200,'Artificial Intelligence','-',2,3,1,0,0,'No Detail','Hebrew/English',0,1,'US$ 5K - 10K',10000,'US$ 6K+',7000).
data('Applied CS','Asia','Israel','Technion - Israel Institute of Technology',165,'Faculty of Computer Science',200,'Applied CS','-',2,3,1,0,0,'No Detail','Hebrew/English',0,1,'US$ 5K - 10K',10000,'US$ 6K+',7000).
data('Network and Security','Asia','Israel','Tel Aviv University',195,'Faculty of Engineering',200,'Network','-',2,3,1,0,0,'No Detail','Hebrew',0,1,'US$ 20K - 25K',25000,'US$ 6K+',7000).
data('Software Engineering','Asia','Israel','Tel Aviv University',195,'Faculty of Engineering',200,'Software Technology','-',2,3,1,0,0,'No Detail','Hebrew',0,1,'US$ 20K - 25K',25000,'US$ 6K+',7000).
data('Network and Security','Asia','Japan ','Keio University',197,'Graduate School of Science and Technology',200,'Network','-',2,2,1,0,0,'No Detail','Japanese',0,1,'US$ 10K - 15K',15000,'US$ 6K+',7000).
data('Software Engineering','Asia','Japan ','Keio University',197,'Graduate School of Science and Technology',200,'Software Technology','-',2,2,1,0,0,'No Detail','Japanese',0,1,'US$ 10K - 15K',15000,'US$ 6K+',7000).
data('Artificial Intelligence','Asia','Japan ','Keio University',197,'Graduate School of Science and Technology',200,'Artificial Intelligence','-',2,2,1,0,0,'No Detail','Japanese',0,1,'US$ 10K - 15K',15000,'US$ 6K+',7000).
data('Applied CS','Asia','Japan ','Keio University',197,'Graduate School of Science and Technology',200,'Applied CS','-',2,2,1,0,0,'No Detail','Japanese',0,1,'US$ 10K - 15K',15000,'US$ 6K+',7000).
